# 04 · Gap-tolerance LME sensitivity analysis

This notebook compares phase-level hypnodensity linear mixed-effects models across six persisted gap tolerances. The 90-second run is the primary analysis; all other tolerances are sensitivity analyses. No figures are generated.

## 1. Imports and parameters

In [ ]:
from pathlib import Path
import warnings

import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
from IPython.display import display

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / 'outputs').is_dir():
    PROJECT_ROOT = PROJECT_ROOT.parent
OUTPUT_ROOT = PROJECT_ROOT / 'outputs'
RESULTS_DIR = OUTPUT_ROOT / 'gap_tolerance_lme_v1'
if RESULTS_DIR.exists():
    raise FileExistsError(f'{RESULTS_DIR} already exists; refusing to overwrite it.')

TOLERANCES = (0, 15, 30, 60, 90, 120)
STAGER = 'gssc'  # persisted label for GSSC
STAGES = ('W', 'N1', 'N2', 'N3', 'R')
PHASES = ('before', 'after', 'late')
CONDITIONS = ('placebo', 'DMT')
PROBABILITIES = tuple(f'prob_{stage}' for stage in STAGES)
CONTRAST_LABELS = {
    'after': 'After difference-in-differences',
    'late': 'Late difference-in-differences',
}
RUN_DIRS = {
    tolerance: OUTPUT_ROOT / f'gap_sensitivity_{tolerance:03d}s_gssc_yasa_sleepfm_cpu_v1'
    for tolerance in TOLERANCES
}
MODEL_FORMULA = (
    'phase_mean ~ C(condition, Treatment(reference=\"placebo\")) * '
    'C(phase, Treatment(reference=\"before\"))'
)
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 30)

## 2. Statistical model description

Epochs are averaged within each `subject × condition × phase × electrode × stager` cell so that the model's observation is a phase-level electrode measurement, rather than an epoch-level pseudo-replicate. Electrodes are retained as separate observations.

For each sleep-stage probability, the model is `phase_mean ~ condition * phase`, with placebo as the condition reference and before as the phase reference. It includes a subject random intercept and an electrode variance component specified as `0 + C(electrode)`. There is no epoch intercept because epochs have already been averaged within phase.

With these references, the selected interactions are exactly `(After − Before)_DMT − (After − Before)_placebo` and `(Late − Before)_DMT − (Late − Before)_placebo`. The 90-second tolerance is the primary analysis; 0, 15, 30, 60, and 120 seconds evaluate sensitivity. Benjamini–Hochberg correction is applied separately within each tolerance across the 30 stager × sleep-stage × contrast tests.

## 3. Load results and average by phase

In [9]:
def load_phase_means(tolerance):
    files = sorted(RUN_DIRS[tolerance].joinpath('recordings').glob('*_inner_hypnodensities.parquet'))
    if not files:
        raise FileNotFoundError(f'No persisted hypnodensity files found for {tolerance} seconds.')
    frames = [pd.read_parquet(file) for file in files]
    table = pd.concat(frames, ignore_index=True)
    table = table.loc[table['stager'].astype(str).eq(STAGER)].copy()
    table['phase'] = table['experimental_label'].astype(str)
    table = table.loc[table['phase'].isin(PHASES)].copy()
    table['condition'] = pd.Categorical(table['condition'], categories=CONDITIONS)
    table['phase'] = pd.Categorical(table['phase'], categories=PHASES, ordered=True)
    keys = ['subject', 'condition', 'phase', 'electrode', 'stager']
    means = table.groupby(keys, observed=True, dropna=False)[list(PROBABILITIES)].mean().reset_index()
    means.insert(0, 'tolerance_seconds', tolerance)
    return means

phase_means = pd.concat([load_phase_means(tolerance) for tolerance in TOLERANCES], ignore_index=True)
phase_means['condition'] = pd.Categorical(phase_means['condition'], categories=CONDITIONS)
phase_means['phase'] = pd.Categorical(phase_means['phase'], categories=PHASES, ordered=True)
display(phase_means.groupby('tolerance_seconds', observed=True).size().rename('phase_mean_observations').to_frame())

                   phase_mean_observations
tolerance_seconds
0                                     3200
15                                    3200
30                                    3200
60                                    3200
90                                    3200
120                                   3200

## 4. Fit the LMEs

In [5]:
def benjamini_hochberg(p_values):
    values = np.asarray(p_values, dtype=float)
    adjusted = np.full(values.shape, np.nan)
    finite = np.flatnonzero(np.isfinite(values))
    if finite.size:
        order = finite[np.argsort(values[finite])]
        ranked = values[order] * finite.size / np.arange(1, finite.size + 1)
        ranked = np.minimum.accumulate(ranked[::-1])[::-1]
        adjusted[order] = np.minimum(ranked, 1.0)
    return adjusted

def interaction_term(params, phase):
    matches = [name for name in params.index if '[T.DMT]' in name and f'[T.{phase}]' in name]
    if len(matches) != 1:
        raise KeyError(f'Expected one DMT × {phase} interaction, found {matches}.')
    return matches[0]

rows = []
for tolerance in TOLERANCES:
    subset_tolerance = phase_means.loc[phase_means['tolerance_seconds'].eq(tolerance)]
    for stage, probability in zip(STAGES, PROBABILITIES):
        data = subset_tolerance[[
            'subject', 'condition', 'phase', 'electrode', probability
        ]].dropna(subset=[probability]).rename(columns={probability: 'phase_mean'}).copy()
        with warnings.catch_warnings():
            warnings.simplefilter('ignore')
            model = smf.mixedlm(
                MODEL_FORMULA, data=data, groups=data['subject'],
                vc_formula={'electrode': '0 + C(electrode)'}, re_formula='1'
            )
            fit = model.fit(reml=False, method='lbfgs', maxiter=400, disp=False)
        confidence = fit.conf_int()
        for phase, label in CONTRAST_LABELS.items():
            term = interaction_term(fit.fe_params, phase)
            rows.append({
                'tolerance_seconds': tolerance, 'stager': 'GSSC', 'sleep_stage': stage,
                'contrast': label, 'estimate': float(fit.fe_params[term]),
                'standard_error': float(fit.bse_fe[term]),
                'ci95_low': float(confidence.loc[term, 0]),
                'ci95_high': float(confidence.loc[term, 1]),
                'z_value': float(fit.tvalues[term]), 'p_value': float(fit.pvalues[term]),
                'n_observations': int(len(data)), 'n_subjects': int(data['subject'].nunique()),
                'converged': bool(fit.converged),
            })

lme_interactions = pd.DataFrame(rows)
lme_interactions['p_fdr_bh'] = (
    lme_interactions.groupby('tolerance_seconds', sort=False)['p_value']
    .transform(benjamini_hochberg)
)
lme_interactions = lme_interactions[[
    'tolerance_seconds', 'stager', 'sleep_stage', 'contrast', 'estimate',
    'standard_error', 'ci95_low', 'ci95_high', 'z_value', 'p_value',
    'p_fdr_bh', 'n_observations', 'n_subjects', 'converged'
]]

## 5. Result tables and persistence

In [7]:
def format_p(value):
    if pd.isna(value):
        return ''
    return f'{value:.2e}' if abs(value) < 1e-4 else f'{value:.4f}'

def dark_table_style(styler):
    return (styler.set_properties(**{'background-color': '#1f2937', 'color': '#f3f4f6'})
                  .set_table_styles([
                      {'selector': 'th', 'props': [('background-color', '#111827'), ('color', '#f9fafb'), ('font-weight', '600')]},
                      {'selector': 'td', 'props': [('border-color', '#374151')]},
                  ]))

def style_results(table):
    numeric = ['estimate', 'standard_error', 'ci95_low', 'ci95_high', 'z_value']
    styler = dark_table_style(table.style).format({column: '{:.4f}' for column in numeric})
    for column in ('p_value', 'p_fdr_bh'):
        styler = styler.format({column: format_p})
    return styler.apply(
        lambda row: ['background-color: #365314; color: #ecfccb' if row['p_fdr_bh'] < 0.05 else '' for _ in row],
        axis=1,
    )

ordered = ['stager', 'sleep_stage', 'contrast', 'tolerance_seconds']
primary_90s = (lme_interactions.loc[lme_interactions['tolerance_seconds'].eq(90)]
               .sort_values(['stager', 'sleep_stage', 'contrast']).reset_index(drop=True))
comparison = lme_interactions.sort_values(ordered).reset_index(drop=True)
summary = comparison.pivot(index=['stager', 'sleep_stage', 'contrast'], columns='tolerance_seconds', values=['estimate', 'p_fdr_bh'])
summary.columns = [f'{metric}_{int(tolerance):03d}s' for metric, tolerance in summary.columns]
summary = summary.reset_index().sort_values(['stager', 'sleep_stage', 'contrast'])

display(style_results(primary_90s))
display(style_results(comparison))
summary_styler = dark_table_style(summary.style)
summary_styler = summary_styler.format({column: format_p for column in summary.columns if column.startswith('p_fdr_bh_')})
summary_styler = summary_styler.format({column: '{:.4f}' for column in summary.columns if column.startswith('estimate_')})
summary_styler = summary_styler.apply(lambda row: [
    'background-color: #365314; color: #ecfccb'
    if column.startswith('p_fdr_bh_') and pd.notna(value) and value < 0.05 else ''
    for column, value in zip(row.index, row)
], axis=1)
display(summary_styler)

# RESULTS_DIR.mkdir(parents=True)
phase_means.to_parquet(RESULTS_DIR / 'phase_means.parquet', index=False)
lme_interactions.to_csv(RESULTS_DIR / 'lme_interactions_all_tolerances.csv', index=False)
primary_90s.to_csv(RESULTS_DIR / 'lme_interactions_primary_90s.csv', index=False)
summary.to_csv(RESULTS_DIR / 'lme_interactions_comparison.csv', index=False)
display(f'Saved results to {RESULTS_DIR}')

'Saved results to /home/rherzoga/Documentos/Projects/Timmerman/dmt_hypnodensities/outputs/gap_tolerance_lme_v1'

In [12]:
primary_0 = lme_interactions.loc[
    lme_interactions["tolerance_seconds"].eq(0)
].copy()

primary_0_after = primary_0.loc[
    primary_0["contrast"].eq("After difference-in-differences")
].copy()

primary_0_late = primary_0.loc[
    primary_0["contrast"].eq("Late difference-in-differences")
].copy()


display("0-second analysis — After difference-in-differences")
display(style_results(primary_0_after))

display("0-second analysis — Late difference-in-differences")
display(style_results(primary_0_late))

'0-second analysis — After difference-in-differences'

'0-second analysis — Late difference-in-differences'

In [ ]:
primary_after = primary_90s.loc[
    primary_90s["contrast"].eq("After difference-in-differences")
].copy()

primary_late = primary_90s.loc[
    primary_90s["contrast"].eq("Late difference-in-differences")
].copy()

all_after = comparison.loc[
    comparison["contrast"].eq("After difference-in-differences")
].copy()

all_late = comparison.loc[
    comparison["contrast"].eq("Late difference-in-differences")
].copy()


display("Primary analysis — After difference-in-differences")
display(style_results(primary_after))

display("Primary analysis — Late difference-in-differences")
display(style_results(primary_late))

display("All tolerances — After difference-in-differences")
display(style_results(all_after))

display("All tolerances — Late difference-in-differences")
display(style_results(all_late))

'Primary analysis — After difference-in-differences'

'Primary analysis — Late difference-in-differences'

'All tolerances — After difference-in-differences'

'All tolerances — Late difference-in-differences'

In [10]:
epoch_counts = []

for tolerance in TOLERANCES:
    files = sorted(
        RUN_DIRS[tolerance]
        .joinpath("recordings")
        .glob("*_inner_hypnodensities.parquet")
    )

    raw = pd.concat(
        [pd.read_parquet(file) for file in files],
        ignore_index=True,
    )

    raw = raw.loc[
        raw["stager"].astype(str).eq(STAGER)
        & raw["experimental_label"].astype(str).isin(PHASES)
    ].copy()

    unique_epochs = raw.drop_duplicates(
        subset=[
            "subject",
            "condition",
            "recording_id",
            "block_id",
            "epoch",
        ]
    )

    counts = (
        unique_epochs
        .groupby(["condition", "subject"], observed=True)
        .size()
        .rename("n_epochs")
        .reset_index()
        .assign(tolerance_seconds=tolerance)
    )

    epoch_counts.append(counts)


epoch_counts = pd.concat(epoch_counts, ignore_index=True)

epoch_counts_table = (
    epoch_counts
    .pivot(
        index=["condition", "subject"],
        columns="tolerance_seconds",
        values="n_epochs",
    )
    .fillna(0)
    .astype(int)
    .rename(columns=lambda tolerance: f"{int(tolerance):03d}s")
    .reset_index()
    .sort_values(["condition", "subject"])
    .reset_index(drop=True)
)

display(epoch_counts_table)

tolerance_seconds condition subject  000s  015s  030s  060s  090s  120s
0                       DMT     P07    18    18    18    18    18    18
1                       DMT     P08    32    32    32    32    32    32
2                       DMT     P09    21    21    21    21    21    21
3                       DMT     P10    35    35    35    35    35    35
4                       DMT     P11     5     5     5     5     5     5
5                       DMT     P12     4     4     4     4     4     4
6                       DMT     P13    15    15    15    15    15    15
7                       DMT     P14     6     6     6     6     6     6
8                       DMT     P15    24    24    24    24    24    24
9                       DMT     P17    41    41    41    41    41    41
10                      DMT     P18    15    15    15    15    15    15
11                      DMT     P19    34    34    34    34    34    34
12                      DMT     P21    29    29    29    29    29    29
13                      DMT     P22    26    26    26    26    26    26
14                      DMT     P23    33    33    33    33    33    33
15                      DMT     P24    18    18    18    18    18    18
16                      DMT     P26    22    22    22    22    22    22
17                      DMT     P28    25    25    25    25    25    25
18                  placebo     P07    38    38    38    38    38    38
19                  placebo     P08    47    47    47    47    47    47
20                  placebo     P09    56    56    56    56    56    56
21                  placebo     P10    50    50    50    50    50    50
22                  placebo     P11    44    44    44    44    44    44
23                  placebo     P12    45    45    45    45    45    45
24                  placebo     P13    49    49    49    49    49    49
25                  placebo     P14    42    42    42    42    42    42
26                  placebo     P15    58    58    58    58    58    58
27                  placebo     P17    56    56    56    56    56    56
28                  placebo     P18    55    55    55    55    55    55
29                  placebo     P19    67    67    67    67    67    67
30                  placebo     P21    55    55    55    55    55    55
31                  placebo     P22    53    53    53    53    53    53
32                  placebo     P23    40    40    40    40    40    40
33                  placebo     P24    26    26    26    26    26    26
34                  placebo     P26    41    41    41    41    41    41
35                  placebo     P28    28    28    28    28    28    28

In [11]:
block_counts = []

for tolerance in TOLERANCES:
    files = sorted(
        RUN_DIRS[tolerance]
        .joinpath("recordings")
        .glob("*_inner_hypnodensities.parquet")
    )

    raw = pd.concat(
        [pd.read_parquet(file) for file in files],
        ignore_index=True,
    )

    raw = raw.loc[
        raw["stager"].astype(str).eq(STAGER)
        & raw["experimental_label"].astype(str).isin(PHASES)
    ].copy()

    unique_blocks = raw.drop_duplicates(
        subset=[
            "subject",
            "condition",
            "recording_id",
            "block_id",
        ]
    )

    counts = (
        unique_blocks
        .groupby(["condition", "subject"], observed=True)
        .size()
        .rename("n_continuous_blocks")
        .reset_index()
        .assign(tolerance_seconds=tolerance)
    )

    block_counts.append(counts)


block_counts = pd.concat(block_counts, ignore_index=True)

block_counts_table = (
    block_counts
    .pivot(
        index=["condition", "subject"],
        columns="tolerance_seconds",
        values="n_continuous_blocks",
    )
    .fillna(0)
    .astype(int)
    .rename(columns=lambda tolerance: f"{int(tolerance):03d}s")
    .reset_index()
    .sort_values(["condition", "subject"])
    .reset_index(drop=True)
)

display(block_counts_table)

tolerance_seconds condition subject  000s  015s  030s  060s  090s  120s
0                       DMT     P07    11    11     8     4     2     2
1                       DMT     P08    25    23    17     8     8     7
2                       DMT     P09    15    15    12     7     6     6
3                       DMT     P10    18    17    15     9     6     5
4                       DMT     P11     5     4     4     3     3     3
5                       DMT     P12     4     4     3     3     2     2
6                       DMT     P13    12    12    12    11     7     6
7                       DMT     P14     6     4     3     3     2     2
8                       DMT     P15    21    18    16    12     6     5
9                       DMT     P17    27    23    17    11     8     7
10                      DMT     P18    10     7     4     4     2     2
11                      DMT     P19    22    19    14     7     5     5
12                      DMT     P21    21    19    13     8     5     4
13                      DMT     P22    20    18    14    12    10     6
14                      DMT     P23    23    19    13     8     6     3
15                      DMT     P24    11     8     6     2     2     2
16                      DMT     P26    15    12     6     5     4     4
17                      DMT     P28    19    17    10     5     5     4
18                  placebo     P07    24    21    16     7     2     2
19                  placebo     P08    29    25    18    11     3     3
20                  placebo     P09    27    25    20     6     4     2
21                  placebo     P10    28    23    15     3     3     3
22                  placebo     P11    22    20    16    10     4     4
23                  placebo     P12    27    25    18     9     4     3
24                  placebo     P13    32    32    23    13     4     1
25                  placebo     P14    30    27    19     9     7     5
26                  placebo     P15    31    27    23     7     2     2
27                  placebo     P17    35    31    20     6     3     2
28                  placebo     P18    36    31    19    11     3     1
29                  placebo     P19    29    26    18     3     3     2
30                  placebo     P21    40    30    21     5     2     2
31                  placebo     P22    30    28    18    10     5     2
32                  placebo     P23    28    26    19    11     6     4
33                  placebo     P24    21    16    13     9     9     6
34                  placebo     P26    27    24    19    13     6     4
35                  placebo     P28    21    20    13     7     5     3